# Generated by Django 4.1 on 2023-11-20 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUsers',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID пользователя')),
                ('username', models.CharField(blank=True, max_length=250, null=True, verbose_name='Имя пользователя')),
                ('first_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Фамилия')),
                ('blocked', models.BooleanField(default=False, verbose_name='Заблокирован')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Персонал')),
                ('messages', models.TextField(default='[]')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default='')),
                ('answer', models.TextField(default='')),
                ('review', models.CharField(max_length=250)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZangerKZ.telegramusers')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
