# Generated by Django 4.1 on 2023-11-20 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID канала')),
                ('name', models.CharField(max_length=250, verbose_name='Название канала')),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'Канал',
                'verbose_name_plural': 'Каналы',
            },
        ),
        migrations.CreateModel(
            name='GPTModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('slug', models.CharField(max_length=250, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
            },
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250, verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('value', models.IntegerField(verbose_name='Количество')),
                ('top', models.BooleanField(default=False, verbose_name='В топе')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
            },
        ),
        migrations.CreateModel(
            name='Promocodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, verbose_name='Код')),
                ('NOR', models.IntegerField(verbose_name='Количество запросов')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Чаевые',
                'verbose_name_plural': 'Чаевые',
            },
        ),
        migrations.CreateModel(
            name='TelegramUsers',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID пользователя')),
                ('username', models.CharField(blank=True, max_length=250, null=True, verbose_name='Имя пользователя')),
                ('first_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Фамилия')),
                ('blocked', models.BooleanField(default=False, verbose_name='Заблокирован')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Персонал')),
                ('RPD', models.IntegerField(verbose_name='Количество ежедневных запросов')),
                ('RPD_BONUS', models.IntegerField(verbose_name='Количество бонусных запросов')),
                ('IPD', models.IntegerField(verbose_name='Количество ежедневных изображений')),
                ('referrals', models.IntegerField(verbose_name='Количество рефералов')),
                ('messages', models.TextField(default='[]', verbose_name='Сообщения')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChatGPT.gptmodels', verbose_name='Модель')),
                ('referrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ChatGPT.telegramusers', verbose_name='Реферер')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
