# Generated by Django 4.1 on 2023-11-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID канала')),
                ('name', models.CharField(max_length=250, verbose_name='Имя канала')),
            ],
            options={
                'verbose_name': 'Канал',
                'verbose_name_plural': 'Каналы',
            },
        ),
        migrations.CreateModel(
            name='TelegramUsers',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID пользователя')),
                ('username', models.CharField(blank=True, max_length=250, null=True, verbose_name='Имя пользователя')),
                ('first_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Фамилия')),
                ('blocked', models.BooleanField(default=False, verbose_name='Заблокирован')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Персонал')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
